// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7-QLU1xoqUPvyQ-vmYgFWI6ml2uJCTM',
    appId: '1:24586260436:web:e173e2f071aae978f1d041',
    messagingSenderId: '24586260436',
    projectId: 'testproject-a104d',
    authDomain: 'testproject-a104d.firebaseapp.com',
    storageBucket: 'testproject-a104d.firebasestorage.app',
    measurementId: 'G-K6Z22PMT8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0chchhXGgMNmD7sPIhBWmJrLxTR3UJU8',
    appId: '1:24586260436:android:0c4f0909dac60cbdf1d041',
    messagingSenderId: '24586260436',
    projectId: 'testproject-a104d',
    storageBucket: 'testproject-a104d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPUCyjIlSZZFgkXj9YifGOB0h3BOuegWk',
    appId: '1:24586260436:ios:9a85e803e811be7af1d041',
    messagingSenderId: '24586260436',
    projectId: 'testproject-a104d',
    storageBucket: 'testproject-a104d.firebasestorage.app',
    iosBundleId: 'com.example.getxWithFirebase',
  );
}
